run:
  timeout: 5m

# all available settings of specific linters
linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    settings:
      printf:
        funcs:
          - printf
          - debugf
          - infof
          - warnf
          - errorf
          - fatalf
          - wrapf
  gocyclo:
    min-complexity: 14
  misspell:
    locale: US
  unparam:
    check-exported: true

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - gosec
    - unconvert
    - goconst
    - misspell
    - unparam
    - prealloc
    - exportloopref
    - gochecknoinits
    - gocritic
    - dupl
    - gocyclo
    - goimports
    - ineffassign
  fast: false

issues:
  exclude-dirs:
    - internal/generated
    - pkg
    - vendor
    - tests
    - lint-rules

  exclude-files:
    - _test.go

  max-same-issues: 0
  new: false