db:
  dialect: postgres
  schema: public
  host: localhost
  port: 5432
  user: doctor_vet
  password: doctor_vet
  name: doctor_vet
  debug: true
  max_idle_conns: 25
  max_open_conns: 25
  conn_max_lifetime: 5m
  ssl: false

public:
  host: "localhost"
  port: 3000
  idle_timeout: 5m
  read_timeout: 10s
  write_timeout: 10s
private:
  host: "localhost"
  port: 3001
  idle_timeout: 5m
  read_timeout: 10s
  write_timeout: 10s
admin:
  host: "localhost"
  port: 3002
  idle_timeout: 5m
  read_timeout: 10s
  write_timeout: 10s
  
keycloak:
  url: "http://localhost:8080/auth"
  realm: "doctor_vet"
  client_id: "doctor_vet_client"
  secret: "SyR9rLjb1aVQXKT7CcgHsyhydVk2CJZ2"
  rsa256: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0W2wf0btjcMeEun6DfVI8ouH1LyAMY/wRAg18/MPjc3RKwmR5ZCK+E7v60peMGwDkXeVwVDco0/3r6UUdaiLr2lCsnZ+v6xn04Gpj7Gy2Bf6ULa/COLexdK8hho9WxITtIAKm6uEDHD0IKb3UG/0EHNVtwOmmm5SoBjaXtwgSvfjxIf7RvE3flk0FNVWADh+nSDwJ75DP6qLJfcXgbXg8OG56YzhYkWIMR8cJ97mVRW5WpsIYTxn+l6txiNI0CVclcsUUBfQqt/duoNwDtnvBCUv9bcgoSBQ41LhNaQeqtuLQtetTxhMW/H0vMj5LDOBnULY2bjxF4Dab+tkeTNDiQIDAQAB"
