-- +goose Up
CREATE TABLE IF NOT EXISTS patient (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fio         VARCHAR(255) NOT NULL,
    phone       VARCHAR(20)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    animal      VARCHAR(100),
    breed       VARCHAR(100),
    gender      VARCHAR(20),
    age         FLOAT,
    is_neutered BOOLEAN NOT NULL DEFAULT FALSE
);

COMMENT ON TABLE patient IS 'Пациент, животное которому будет оказано лечение';
COMMENT ON COLUMN patient.id IS 'ID записи';
COMMENT ON COLUMN patient.fio IS 'ФИО хозяина животного';
COMMENT ON COLUMN patient.phone IS 'Телефон хозяина животного';
COMMENT ON COLUMN patient.name IS 'Кличка животного';
COMMENT ON COLUMN patient.animal IS 'Вид животного (собака, кошка)';
COMMENT ON COLUMN patient.breed IS 'Порода животного';
COMMENT ON COLUMN patient.gender IS 'Пол животного';
COMMENT ON COLUMN patient.age IS 'Возраст животного';
COMMENT ON COLUMN patient.is_neutered IS 'Кастрат или нет';

CREATE TABLE IF NOT EXISTS treatment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id  INT NOT NULL REFERENCES patient(id) ON DELETE CASCADE,
    doctor_id   UUID,
    temperature FLOAT,
    status      VARCHAR(50),
    created_at  timestamptz    default now()  not null,
    updated_at  timestamptz    default now()  not null,
    begin_at    timestamptz,
    end_at      timestamptz,
    comment     TEXT,
    is_active   INT NOT NULL DEFAULT 1,
    weight      FLOAT,
    add_info    jsonb
);

COMMENT ON TABLE treatment IS 'Лечение, которое будет оказано животному';
COMMENT ON COLUMN treatment.id IS 'ID записи';
COMMENT ON COLUMN treatment.patient_id IS 'ID пациента';
COMMENT ON COLUMN treatment.doctor_id IS 'ID доктора который будет проводить лечение';
COMMENT ON COLUMN treatment.temperature IS 'Температура животного';
COMMENT ON COLUMN treatment.status IS 'На каком этапе лечение (в ожидании, в процессе, отклонено)';
COMMENT ON COLUMN treatment.created_at IS 'Дата создания лечения';
COMMENT ON COLUMN treatment.updated_at IS 'Дата обновления лечения';
COMMENT ON COLUMN treatment.begin_at IS 'Дата начала лечения';
COMMENT ON COLUMN treatment.end_at IS 'Дата полного окончания лечения';
COMMENT ON COLUMN treatment.comment IS 'Комментарий от врача';
COMMENT ON COLUMN treatment.is_active IS 'Открыто или закрыто лечение (1 - открыто, 0 - закрыто)';
COMMENT ON COLUMN treatment.weight IS 'Вес животного';
COMMENT ON COLUMN treatment.add_info IS 'Доп поля';

CREATE TABLE IF NOT EXISTS prescription (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    treatment_id    INT NOT NULL REFERENCES treatment(id) ON DELETE CASCADE,
    name            VARCHAR(100) NOT NULL,
    dose            FLOAT NOT NULL,
    course          VARCHAR(100) NOT NULL,
    category        VARCHAR(100),
    option          VARCHAR(255),
    created_at      timestamptz    default now()  not null,
    updated_at      timestamptz    default now()  not null
);

COMMENT ON TABLE prescription IS 'Препараты которые были сделаны или назначены врачом';
COMMENT ON COLUMN prescription.id IS 'ID записи';
COMMENT ON COLUMN prescription.treatment_id IS 'ID лечения';
COMMENT ON COLUMN prescription.name IS 'Название препарата';
COMMENT ON COLUMN prescription.dose IS 'Дозирование препарата';
COMMENT ON COLUMN prescription.course IS 'Курс получения препарата (2 раза в день после еды)';
COMMENT ON COLUMN prescription.category IS 'К какой категории относится препарат(витамин, антибиотик)';
COMMENT ON COLUMN prescription.option IS 'Доп поле для уточнения';
COMMENT ON COLUMN prescription.created_at IS 'Дата назначения препарата';
COMMENT ON COLUMN prescription.updated_at IS 'Дата обновления препарата';

-- +goose Down
DROP TABLE IF EXISTS prescription;
DROP TABLE IF EXISTS treatment;
DROP TABLE IF EXISTS patient;
