-- +goose Up
CREATE TABLE IF NOT EXISTS preparation (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    dose        FLOAT NOT NULL,
    course      VARCHAR(100) NOT NULL,
    category    VARCHAR(100),
    option      VARCHAR(255)
);
COMMENT ON TABLE preparation IS 'Рекомендованный препарат по симптому';
COMMENT ON COLUMN preparation.id IS 'ID записи';
COMMENT ON COLUMN preparation.name IS 'Название препарата';
COMMENT ON COLUMN preparation.dose IS 'Дозирование препарата';
COMMENT ON COLUMN preparation.course IS 'Курс получения препарата (2 раза в день после еды)';
COMMENT ON COLUMN preparation.category IS 'К какой категории относится препарат(витамин, антибиотик)';
COMMENT ON COLUMN preparation.option IS 'Доп поле для уточнения';


CREATE TABLE IF NOT EXISTS reference (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255),
    type  VARCHAR(30)
);
COMMENT ON TABLE reference IS 'Справочник';
COMMENT ON COLUMN reference.id IS 'ID записи';
COMMENT ON COLUMN reference.name IS 'Название записи';
COMMENT ON COLUMN reference.type IS 'Тип справочник (symptoms, animal, breed)';

INSERT INTO reference (name, type)
VALUES
    ('анемия', 'symptoms'),
    ('анорексия', 'symptoms'),
    ('обезвоживание', 'symptoms'),
    ('диарея с кровью', 'symptoms'),
    ('диарея без крови', 'symptoms'),
    ('рвота c желчью', 'symptoms'),
    ('рвота с кровью', 'symptoms'),
    ('рвота без крови', 'symptoms'),
    ('высокая температура до 40', 'symptoms'),
    ('высокая температура выше 40', 'symptoms'),
    ('алопеции единичная', 'symptoms'),
    ('алопеции множественная', 'symptoms'),
    ('открытая рана гнойная', 'symptoms'),
    ('открытая рана условно чистая', 'symptoms'),
    ('постоперационая рана воспаленная', 'symptoms'),
    ('постоперационая рана условно чистая', 'symptoms'),
    ('воспаление в ротовой полости', 'symptoms'),
    ('зуд воспаление, выпадение шерсти', 'symptoms'),
    ('увеличенные почки', 'symptoms'),
    ('кашель', 'symptoms'),
    ('гипоксия', 'symptoms'),
    ('выделения из глаз гнойные', 'symptoms'),
    ('выделения из глаз прозрачные', 'symptoms');

CREATE TABLE IF NOT EXISTS preliminary_diagnosis (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL,
    option      jsonb
);
COMMENT ON TABLE preliminary_diagnosis IS 'Предварительный диагноз';
COMMENT ON COLUMN preliminary_diagnosis.id IS 'ID записи';
COMMENT ON COLUMN preliminary_diagnosis.name IS 'Название записи';
COMMENT ON COLUMN preliminary_diagnosis.option IS 'Возможные доп анализы (анализ крови, узи, бак посев)';

CREATE TABLE IF NOT EXISTS relation (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    preparation_id                  BIGINT REFERENCES preparation(id) ON DELETE CASCADE,
    preliminary_diagnosis_id        BIGINT REFERENCES preliminary_diagnosis(id) ON DELETE CASCADE,
    reference_id                    BIGINT REFERENCES reference(id) ON DELETE CASCADE,
    option                          jsonb
);
COMMENT ON TABLE relation IS 'Связи симптомов с препаратами и предварительным диагнозом';
COMMENT ON COLUMN relation.id IS 'ID записи';
COMMENT ON COLUMN relation.preparation_id IS 'ID препарата';
COMMENT ON COLUMN relation.preliminary_diagnosis_id IS 'ID предварительного диагноза';
COMMENT ON COLUMN relation.reference_id IS 'ID симптома из справочника';
COMMENT ON COLUMN relation.option IS 'Возможные доп поля';

CREATE INDEX idx_preparation_id ON relation(preparation_id);
CREATE INDEX idx_reference_id ON relation(reference_id);

-- +goose Down
DROP TABLE IF EXISTS reference;
DROP TABLE IF EXISTS preparation;
DROP TABLE IF EXISTS preliminary_diagnosis;
DROP TABLE IF EXISTS relation;
DROP INDEX IF EXISTS idx_preparation_id;
DROP INDEX IF EXISTS idx_reference_id;
