-- +goose Up
CREATE TABLE IF NOT EXISTS patient (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fio         VARCHAR(255) NOT NULL,
    phone       VARCHAR(20),
    address     TEXT,
    animal      VARCHAR(100),
    name        VARCHAR(100),
    breed       VARCHAR(100),
    gender      VARCHAR(20),
    age         FLOAT,
    is_neutered BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS treatment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id  INT NOT NULL REFERENCES patient(id) ON DELETE CASCADE,
    doctor_id   UUID,
    temperature FLOAT,
    status      VARCHAR(50),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    begin_at    TIMESTAMP,
    end_at      TIMESTAMP,
    comment     TEXT,
    is_active   INT NOT NULL DEFAULT 1,
    weight      FLOAT
);

CREATE TABLE IF NOT EXISTS prescription (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    treatment_id    INT NOT NULL REFERENCES treatment(id) ON DELETE CASCADE,
    preparation     VARCHAR(255),
    dose            VARCHAR(100),
    course          VARCHAR(255),
    amount          VARCHAR(100),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- +goose Down
DROP TABLE IF EXISTS prescription;
DROP TABLE IF EXISTS treatment;
DROP TABLE IF EXISTS patient;
